-- userinfo default value --
INSERT INTO USER_INFO(ID,USR_EMP_ID,FULL_NAME,PASSWORD,STATUS,CREATED_DATE,ROLE,REFRESH_TOKEN)
values(1,1001,'Team1','$2a$11$3sNx4.2uMLIW3klSDv4mPeN88B72hw/eGA4YU.pKFGsNoTxfOk4R2',true,'2020-01-01','admin','');

INSERT INTO USER_INFO(ID,USR_EMP_ID,FULL_NAME,PASSWORD,STATUS,CREATED_DATE,ROLE,REFRESH_TOKEN)
values(2,1234,'Team2','$2a$11$3sNx4.2uMLIW3klSDv4mPeN88B72hw/eGA4YU.pKFGsNoTxfOk4R2',true,'2020-01-01','admin','');

-- Room info --
INSERT INTO ROOM_INFO(ID, ROOM_NAME) values(1,'GLASSDOOR1');
INSERT INTO ROOM_INFO(ID, ROOM_NAME) values(2,'GLASSDOOR2');
INSERT INTO ROOM_INFO(ID, ROOM_NAME) values(3,'GLASSDOOR3');

-- Booking_Purpose --
INSERT INTO BOOKING_PURPOSE(PURPOSE_ID, PURPOSE) values(1,'Stand up');
INSERT INTO BOOKING_PURPOSE(PURPOSE_ID, PURPOSE) values(2,'Sprint planning');
INSERT INTO BOOKING_PURPOSE(PURPOSE_ID, PURPOSE) values(3,'Retro');
INSERT INTO BOOKING_PURPOSE(PURPOSE_ID, PURPOSE) values(4,'Grooming');
INSERT INTO BOOKING_PURPOSE(PURPOSE_ID, PURPOSE) values(5,'Adhoc meeting');

-- Default Booking Entry for testing purpose --
INSERT INTO BOOKING_INFO(ID,ROOM_INFO_ID, USER_INFO_ID,BOOKING_START_DATE,BOOKING_STARTTIME,BOOKING_ENDTIME,MEETING_TYPE_PURPOSE_ID,CREATEDON)
values(1,1,1,'2018-10-01','11:30','12:00',1,'2020-12-31 23:59:59');
INSERT INTO BOOKING_INFO(ID,ROOM_INFO_ID, USER_INFO_ID,BOOKING_START_DATE,BOOKING_STARTTIME,BOOKING_ENDTIME,MEETING_TYPE_PURPOSE_ID,CREATEDON)
values(2,2,1,'2020-03-21','10:30','12:00','2','2020-12-31 23:59:59');
INSERT INTO BOOKING_INFO(ID,ROOM_INFO_ID, USER_INFO_ID,BOOKING_START_DATE,BOOKING_STARTTIME,BOOKING_ENDTIME,MEETING_TYPE_PURPOSE_ID,CREATEDON)
values(3,2,2,'2019-11-01','10:30','12:00','3','2020-12-31 23:59:59');     