-- userinfo default value --
INSERT INTO USER_INFO(ID,USR_EMP_ID,FULL_NAME,PASSWORD,STATUS,CREATED_DATE,ROLE,REFRESH_TOKEN)
values(1,1001,'Team1','$2a$11$3sNx4.2uMLIW3klSDv4mPeN88B72hw/eGA4YU.pKFGsNoTxfOk4R2',true,'2020-01-01','admin','');

INSERT INTO USER_INFO(ID,USR_EMP_ID,FULL_NAME,PASSWORD,STATUS,CREATED_DATE,ROLE,REFRESH_TOKEN)
values(2,1234,'Team2','$2a$11$3sNx4.2uMLIW3klSDv4mPeN88B72hw/eGA4YU.pKFGsNoTxfOk4R2',true,'2020-01-01','admin','');

-- Room info --
INSERT INTO ROOM_INFO(ID, ROOM_NAME) values(1,'GLASSDOOR1');
INSERT INTO ROOM_INFO(ID, ROOM_NAME) values(2,'GLASSDOOR2');
INSERT INTO ROOM_INFO(ID, ROOM_NAME) values(3,'GLASSDOOR3');

-- Booking_Purpose --
INSERT INTO BOOKING_PURPOSE(PURPOSE_ID, PURPOSE) values(1,'Stand up');
INSERT INTO BOOKING_PURPOSE(PURPOSE_ID, PURPOSE) values(2,'Sprint planning');
INSERT INTO BOOKING_PURPOSE(PURPOSE_ID, PURPOSE) values(3,'Retro');
INSERT INTO BOOKING_PURPOSE(PURPOSE_ID, PURPOSE) values(4,'Grooming');
INSERT INTO BOOKING_PURPOSE(PURPOSE_ID, PURPOSE) values(5,'Adhoc meeting');
